### ISSUE TITLE
problem reading timestamp from filename

### ISSUE THREAD

**Issue by cazaudo** [Project-OSmOSE/OSEkit#224]
I got the following error message : 
ValueError: The date template does not match any set of character in the file name /home/datawork-osmose/dataset/DCLDE2015_HF/CINMS_B/data/audio/original/CINMS17B_DL37_111226_000500.x.flac
Make sure you are not forgetting separator characters, or use the offset parameter.

but is there still an offset parameter available ? i cannot find it anymore

**Comment by cazaudo** [comment]
update : it worked after prefixing the timestamp filename with '20' , but should work on "111226_000500" no ?

**Comment by Gautzilla** [comment]
Depends on what your [strftime date template](https://strftime.org/) is:

|code|example|definition|
|:---:|:---:|:---:|
|%y|13|Year without century as a zero-padded decimal number.|
|%Y|2013|Year with century as a decimal number.|

If your date_template uses %Y, it will expect four digits to represent the year. With your `"111226_000500"` date string, `%y%m%d_%H%M%S` will work but `%Y%m%d_%H%M%S` will not.

Note that the date template is searched within the string (it can be located anywhere in the string), thus the opposite is not true: both date_template would work with ` "20111226_000500"`, because the one using %Y (2 digits year) will also be found: _20_**111226_000500**

I am still working on [the integration of the timestamp features within the codebase](https://github.com/Gautzilla/OSEkit/tree/refactor/timestamp_utils_integration), but it's taking some time since it leads me to [larger refactoring to properly integrate the changes](https://github.com/Gautzilla/OSEkit/tree/refactor/dataset-build).

You can find examples of the datetime parsing in the `test_strptime_from_text` and `test_strptime_from_text_errors` tests in [test_timestamp_utils.py](https://github.com/Project-OSmOSE/OSEkit/blob/main/tests/test_timestamp_utils.py).

**Comment by cazaudo** [comment]
ah I did not know that ! thanks for the reminder ,  i think this should go somewhere in our documentation or even better directly be addressed in the try-except part of the code in a transparent way for the user ?

**Comment by Gautzilla** [comment]
> ah I did not know that ! thanks for the reminder , i think this should go somewhere in our documentation or even better directly be addressed in the try-except part of the code in a transparent way for the user ?

Yup, I simplified the usage of timestamps but it hasn't been fully integrated to the codebase yet. I'm working on it in #216. For now, the link to [strftime.org](https://strftime.org/) is provided in the docstring, but an exhaustive documentation will of course be needed!
